---
- hosts: localhost
  become: True
  become_user: root
  pre_tasks:
    - name: Install roles
      shell: ansible-galaxy install "{{ item }}"
      with_items:
      - nolte.minecraft
  roles:
  - nolte.minecraft