---
- hosts: localhost
  become: True
  pre-tasks:
    - name: Install roles
      become: True
        shell: "ansible-galaxy install {{item}}"
      loop:
      - nolte.minecraft
  roles:
  - nolte.minecraft
