---
- hosts: localhost
  become: True
  pre-tasks:
    - name: Install roles
      become: True
      shell: ansible-galaxy install "{{ item }}"
      with_items:
      - nolte.minecraft
  roles:
  - nolte.minecraft
