---
- hosts: localhost
  become: True
  pre_tasks:
    - name: Install roles
      shell: ansible-galaxy install --roles-path /home/ubuntu/.ansible/roles "{{ item }}"
      with_items:
      - nolte.minecraft
  roles:
  - nolte.minecraft